exclude: [ Gemfile, Gemfile.lock, Procfile, vendor, gems, README.md]

sitename:  The Foreman
tagline: The Foreman is a complete lifecycle management tool for physical and virtual servers.
description: Through deep integration with configuration management, DHCP, DNS, TFTP, and PXE-based unattended installations, Foreman manages every stage of the lifecycle of your physical or virtual servers. The Foreman provides comprehensive, auditable interaction facilities including a web frontend and robust, RESTful API.

production_url : http://theforeman.org
url: http://theforeman.org
baseurl: /

safe:        false

future:      false
pygments:    true
markdown:    rdiscount

navigation:
- text: Learn more
  url: learn_more.html
- text: Getting started
  url:  manuals/1.3/quickstart_guide.html
- text: Videos
  url: media.html

